include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - project: gitlab-org/frontend/untamper-my-lockfile
    file: .gitlab-ci-template.yml

image: node:12

stages:
  - test

.install: &install
  yarn install

lint:
  stage: test
  before_script:
    - *install
  script:
    - yarn eslint
    - yarn prettier

test:
  stage: test
  before_script:
    - *install
  script:
    - yarn test
