include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - project: gitlab-org/frontend/untamper-my-lockfile
    file: .gitlab-ci-template.yml

image: node:12

stages:
  - test

.cache-template: &cache-template
  paths:
    - node_modules/
  key:
    files:
      - .gitlab-ci.yml
      - yarn.lock
    prefix: node_modules  

.yarn_install:
  before_script:
    - yarn install --frozen-lockfile
  cache:
    <<: *cache-template
    policy: pull

lint:
  stage: test
  extends: [.yarn_install]
  script:
    - yarn eslint
    - yarn prettier

test:
  stage: test
  extends: [.yarn_install]
  script:
    - yarn test
