include:
  - project: gitlab-org/frontend/untamper-my-lockfile
    file: .gitlab-ci-template.yml

image: node:12

stages:
  - test

.install: &install
  yarn install

lint:
  stage: test
  before_script:
    - *install
  script:
    - yarn eslint
    - yarn prettier

test:
  stage: test
  before_script:
    - *install
  script:
    - yarn test